import './globals.css'

export const metadata = {
  title: 'BASIC-CRUD-GOLANG-NEXT.JS',
  description: 'Generated by BASIC-CRUD-GOLANG-NEXT.JS',
  icons: {
    // gunakan path absolut dari folder public
    icon: "/image/title-image.jpg",
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Doto:wght@100..900&family=Kablammo&display=swap"
          rel="stylesheet"
        />
        <link href="https://fonts.googleapis.com/css2?family=Asimovian&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Libertinus+Serif+Display&display=swap" rel="stylesheet" />
      </head>
      <body>{children}</body>
    </html>
  )
}
